### ISSUE TITLE
Normal for Web Inspector to show double image loading?

### ISSUE THREAD

**Issue by tabrindle** [dpogue/cordova-plugin-webp#2]
Is it normal for this plugin to show in Safari web inspector that the image is loaded twice? 

I am assuming this has to do with the image being decoded, as web inspector does not show the original size of the webp image, just what I am assuming is the decoded size. Inspector is showing 13022.webp as 180k where the source image is actually 9k.

<img width="1060" alt="screen shot 2016-03-09 at 10 11 27 am" src="https://cloud.githubusercontent.com/assets/2925048/13639572/571c4608-e5df-11e5-86ba-518f8a11f52a.png">

I just want to make sure it isn't actually getting transferred twice.

Thanks for your work on this plugin!

**Comment by dpogue** [comment]
hmm, my test case has mostly been taking the default Hello Cordova app and replacing the Cordova logo png with a webp file.

In that case, I only see the image transferred one:
<img width="735" alt="screen shot 2016-03-09 at 18 10 30" src="https://cloud.githubusercontent.com/assets/241708/13657231/6d442a16-e622-11e5-96e9-8e790d65a99e.png">

Worth noting that the 33.04KB transferred is the decrypted size, the actual webp file is only 4.5KB on disk.

I'll try another test with a remote file...

**Comment by dpogue** [comment]
Sadly, I don't see the issue with a remote file either, and in that case I see a difference between the size and transferred numbers:
<img width="649" alt="screen shot 2016-03-09 at 18 18 39" src="https://cloud.githubusercontent.com/assets/241708/13657343/7421ebec-e623-11e5-8301-11209cad5c34.png">

From your screenshot, it looks as though the decrypted image is being transferred twice, which is definitely not the intent. Maybe the server is doing some sort of Accept header or User-Agent sniffing and deciding that it shouldn't serve WebP?

**Comment by tabrindle** [comment]
Hello, thanks for your assistance, I believe I've found the issue, and it has nothing to do with your plugin.

Turns out my JS framework had a bug that it was requesting the image twice, but I never would have found it without your help, Thanks!  

For what it's worth, it works fine with iOS 9.3, using cordova 5.3.3, and cordova-ios 3.9.2
