### ISSUE TITLE
WkWebView compatibility

### ISSUE THREAD

**Issue by mnutkiewicz** [dpogue/cordova-plugin-webp#4]
Is there any chance of this plugin supporting WkWebView?

**Comment by dpogue** [comment]
Unfortunately not, because WKWebView doesn't support intercepting requests and replacing the response via NSURLProtocol. You'd have to use something like http://webpjs.appspot.com/ instead. 😢 

There is potentially some good news though: the iOS 10 beta has native support for WebP images.

**Comment by dpogue** [comment]
But sadly that WebP support was dropped from the latest iOS10 betas: https://twitter.com/grorgwork/status/760205585044217856 :(

**Comment by tryhardest** [comment]
Was it ever returned (4 years on) do you use webP in your iOS Cordova apps dpogue? Even Android apps for that matter with a iOS fallback to png or jpg?

**Comment by dpogue** [comment]
We did some tests and found that in most of our cases, it wasn't worth using WebP if we also had to bundle a fallback image in the app bundle.

WKWebView currently does not support WebP and there is no way to add support for it using NSURLProtocol. It *might* be enabled in iOS 14, but that's not guaranteed and doesn't provide a solution for earlier versions.

**Comment by tryhardest** [comment]
Thanks. That makes sense for when the img requires bundling.

For your network requested imgs do you just convert server-side and send to Android client as webP? I was looking at the Squoosh size app comparison and the webP compression is hard to argue with.

**Comment by dpogue** [comment]
We've just been sticking to PNG and JPEG, and using tools like pngquant, zopflipng, guetzli, and mozjpeg to recompress them.
