### ISSUE TITLE
Plugin re-installing on cordova prepare

### ISSUE THREAD

**Issue by tabrindle** [dpogue/cordova-plugin-webp#5]
It seems if you save this plugin in your config.xml as `<plugin name="cordova-plugin-webp" spec="~1.2.0" />`, on each run of `cordova prepare` it will attempt to reinstall the plugin, only to see that it is already installed. 

```
Discovered plugin "cordova-plugin-webp" in config.xml. Adding it to the project
Fetching plugin "cordova-plugin-webp@~1.2.0" via npm
Plugin "ca.dpogue.webp" already installed on android.
Plugin "ca.dpogue.webp" already installed on ios.
```

The only way to fix this is to save it using the old plugin name like this: `<plugin name="ca.dpogue.webp" spec="~1.2.0" />`, as still described in the plugin.xml

This doesn't impact function, but does lead to some confusion where the plugin id is `id="ca.dpogue.webp"` but the repo name is `cordova-plugin-webp`, and the npm package is named `cordova-plugin-webp`

I believe that if the id is changed in the plugin.xml, this will no longer be an issue.

**Comment by dpogue** [comment]
I just pushed a v2.0.0 of the plugin, which has been completely renamed to `cordova-plugin-webp` and also updates libwebp to 0.5.1.

**Comment by tabrindle** [comment]
Thanks! That was a really quick turn around. I will test it first thing tomorrow morning.
