### ISSUE TITLE
Format detection issue

### ISSUE THREAD

**Issue by julienroubieu** [dpogue/cordova-plugin-webp#7]
Hello @dpogue,

I have a issue in my app because of the way we serve pictures: they are proxied by Cloudinary (http://cloudinary.com/documentation/fetch_remote_images), and therefore the URL ends with the original image file extension (jpg) instead of webp.
As a result, I guess `canInitWithRequest` returns false and the image fails to load.

Ex: http://res.cloudinary.com/demo/image/fetch/w_300,f_webp/http://upload.wikimedia.org/wikipedia/commons/0/0c/Scarlett_Johansson_C%C3%A9sars_2014.jpg

Do you see another way to trigger the plugin with such URLs?

**Comment by dpogue** [comment]
This should work with `cdvwebp=true` in v2.2.0.
